FROM python:3.10-slim-buster

RUN apt-get update
RUN apt install -y build-essential
RUN apt-get -y install python3-dev
RUN apt-get install -y libsndfile1-dev

COPY training_inference.py ./training_inference.py
COPY utils.py ./utils.py
COPY api.py ./api.py
COPY requirements.txt ./requirements.txt

RUN pip3 install -r requirements.txt

CMD [ "python3", "-W ignore" ,"api.py"]