FROM python:3.10-slim-buster

RUN apt-get update
RUN apt install -y build-essential
RUN apt-get -y install python3-dev
RUN apt-get install -y libsndfile1-dev

COPY . . 

RUN pip3 install -r requirements.txt

CMD [ "python3", "-W ignore" ,"training_inference.py"]