# Generated by Django 3.2.3 on 2022-07-31 19:15

import colorfield.fields
from django.db import migrations, models
import enumchoicefield.fields
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(help_text='Name of the label', max_length=256, primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(blank=True, default='#74deed', help_text='Color given to the label (optional)', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Prediction Model title', max_length=256, null=True, unique=True)),
                ('output_labels', models.TextField(blank=True, default='', help_text='Prediction Model output labels', null=True)),
                ('weight_file', models.FileField(blank=True, help_text='Prediction Model weights file', upload_to='model_weights')),
                ('test_dataset', models.FileField(blank=True, help_text='Prediction Model test dataset', upload_to='model_datasets')),
                ('current_accuracy_precentage', models.FloatField(blank=True, default=0, help_text='Current accuracy percentage', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Project title', max_length=256, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Project description', null=True)),
                ('instructions', models.TextField(blank=True, default='', help_text='Project instructions', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Project logo', upload_to='images')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time of project creation')),
                ('users_can_see_other_queues', models.BooleanField(default=False, help_text='<b>If false, annotators will see only tasks assigned to them</b>')),
                ('project_type', enumchoicefield.fields.EnumChoiceField(default=projects.models.Project_type(1), enum_class=projects.models.Project_type, help_text='Specify the type of the annotation (Audio, image or Video)', max_length=5)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
