# Generated by Django 3.2.3 on 2022-07-31 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotators',
            field=models.ManyToManyField(blank=True, help_text='Annotators for the project', related_name='project_annotator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(help_text='Labels used by annotators to annotate', to='projects.Label'),
        ),
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Managers for the project', related_name='project_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='prediction_model',
            field=models.ForeignKey(blank=True, default='', help_text='Prediciton Model for the project', on_delete=django.db.models.deletion.CASCADE, to='projects.predictionmodels', to_field='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Reviewers who will review annotations', related_name='project_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent label of the label (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.label'),
        ),
    ]
