# Generated by Django 3.2.3 on 2022-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_prediction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodels',
            name='image_repo',
            field=models.TextField(blank=True, default='', help_text='Prediction Model image repository to pull from.', null=True),
        ),
    ]
