# Generated by Django 3.2.3 on 2022-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_predictionmodels_image_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodels',
            name='current_loss_precentage',
            field=models.FloatField(blank=True, default=0, help_text='Current loss percentage', null=True),
        ),
    ]
