# Generated by Django 3.2.3 on 2022-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_predictionmodels_current_loss_precentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionmodels',
            name='image_repo',
        ),
        migrations.RemoveField(
            model_name='predictionmodels',
            name='test_dataset',
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='docker_configuration_yaml_file',
            field=models.FileField(blank=True, help_text='Docker Configuration YAML file.', upload_to='model_yaml_files'),
        ),
    ]
