# Generated by Django 3.2.3 on 2022-07-31 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Annotators who will annotate the task', related_name='task_annotators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='Project to which the task belongs', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='annotation',
            field=models.ForeignKey(help_text='Annotation reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_reviewed', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewed_by',
            field=models.ForeignKey(help_text='Reviewer who made the review', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='project',
            field=models.ForeignKey(help_text='Project to which the annotation belongs', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='task',
            field=models.ForeignKey(help_text='Task to which the annotation belongs', on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(help_text='User who made the annotation', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('reviewed_by', 'annotation')},
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('user', 'task')},
        ),
    ]
